from manim import *

class FormulaAnimation(Scene):
    def construct(self):
        t1 = MathTex(r"\left ( 2ab+1 \right ) \left ( a+b \right ) =2ab\left ( a+b \right ) +\left ( a+b \right ) ")
        t2 = MathTex(r"2ab\left ( a+b \right ) +\left ( a+b \right ) =6ab")
        t3 = MathTex(r"\frac{2ab\left ( a+b \right ) }{ab} +\frac{a+b}{ab}=\frac{6ab}{ab}  ")
        t4 = MathTex(r"2\left ( a+b \right )+\frac{a+b}{ab}=6")
       # t3 = MathTex(r"\frac{2ab\left ( a+b \right )}{ab}  +\frac{\left ( a+b \right )}{ab}  =\frac{6ab}{ab} ")
       # t4 = MathTex(r"so \space \space that \space \space \space \space 2\left ( a+b \right ) +\frac{a+b}{ab} =6")
        t5 = MathTex(r"we\space \space know:a+b\ge 2\sqrt{ab} ")
        t6 = MathTex(r"so \space \space \frac { \left ( a+b \right )^{2} }{4} \ge ab")

        t7 = MathTex(r"so\space we \space suppose: ab = \frac{ \left (  a+b\right ) ^{2} }{4}")

        t8 = MathTex(r"then\space suppose:x=a+b")
        t9 = MathTex(r"so:2\left ( a+b \right ) +\frac{a+b}{ab} =6")
        t10 = MathTex(r"2x+\frac{x}{\frac{\left ( a+b \right )^{2}  }{4} }=6")
        t11 = MathTex(r"2x+\frac{4}{x}=6")
        t12 = MathTex(r"2x^{2}+4=6x")
        t13 = MathTex(r"x_{1}=1,x_{2}=2")
        t14 = MathTex(r"so:min \space or\space max\space of\space \left ( a+b \right )\space is")
        t15 = MathTex(r"1\space  and \space 2")
        t16 = MathTex(r"so:a+b\in [1,2]")
        t17 = MathTex(r"c\in \left \{ c|1\le c\le 2 \right \}")
       # t11 = MathTex(r"")
       # t9 = MathTex(r"\begin{array}{1}so:2\left ( a+b \right ) +\frac{a+b}{ab} =6 \\2x+\frac{x}{\frac{\left ( a+b \right )^{2}  }{4} }=6 \\2x+\frac{4}{x}=6 \\2x^{2}+4=6x \\x_{1}=1,x_{2}=2     \end{array}")

       # t10 = MathTex(r"\begin{array}{1}so:min \space or\space max\space of\space \left ( a+b \right )\space is\\1\space  and \space 2 \\so:a+b\in [1,2]\\c\in \left \{ c|1\le c\le 2 \right \}        \end{array}")
        
        self.play(FadeIn(t1))
        self.wait(2)
        self.play(ReplacementTransform(t1,t2))
        self.wait(2)
        self.play(ReplacementTransform(t2,t3))
        self.wait(2)
        self.play(ReplacementTransform(t3,t4))
        self.wait(2)
        self.play(ReplacementTransform(t4,t5))
        self.wait(2)
        self.play(ReplacementTransform(t5,t6))
        self.wait(2)
        self.play(ReplacementTransform(t6,t7))
        self.wait(2)
        self.play(ReplacementTransform(t7,t8))
        self.wait(2)
        self.play(ReplacementTransform(t8,t9))
        self.wait(2)
        self.play(ReplacementTransform(t9,t10))
        self.wait(2)
        self.play(ReplacementTransform(t10,t11))
        self.wait(2)
        self.play(ReplacementTransform(t11,t12))
        self.wait(2)
        self.play(ReplacementTransform(t12,t13))
        self.wait(2)
        self.play(ReplacementTransform(t13,t14))
        self.wait(2)
        self.play(ReplacementTransform(t14,t15))
        self.wait(2)
        self.play(ReplacementTransform(t15,t16))
        self.wait(2)
        self.play(ReplacementTransform(t16,t17))
        self.wait(2)
       # self.play(ReplacementTransform(t8,t9))
        self.wait(5)
       # self.play(ReplacementTransform(t9,t10))
        self.wait(8)